modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.bedgunwars]]
modId = "tacz"
mandatory = true
versionRange = "[1.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bedgunwars]]
modId = "lrtactical"
mandatory = true
versionRange = "[0.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bedgunwars]]
modId = "geckolib"
mandatory = false
versionRange = "[4.4.4,5)"
ordering = "NONE"
side = "BOTH"